# -*- coding: utf-8 -*-
"""baseline_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4WVWQCYHVbr8VqzBMcdEALztZUFcWLm

# Baseline: BERT + SASRec Baseline Recommendation System

This notebook implements a **baseline sequential recommendation system** using:

- **BERT embeddings** for item representation
- **Transformer-based SASRec model** for sequence modeling

### Objective
Predict the **next item a user will interact with** based on past interactions.

##  Step 1: Mount Drive & Load Dataset

- Mount Google Drive
- Extract dataset into Colab environment
- Prepare data directory
"""

from google.colab import drive
drive.mount('/content/drive')

# PATH
!unzip -q "/content/drive/MyDrive/NLP_project_repo/data/Movies_and_TV_data.zip" -d "/content/data"

"""## Step 2: Install Dependencies

Install required libraries such as:
- Transformers
- PyTorch
"""

!pip install transformers -q

"""##  Step 3: Import Modules

Import all modularized project files from the `src/` directory.
"""

import os
import sys
import torch
import torch.nn.functional as F
import numpy as np
from torch.utils.data import DataLoader
from tqdm import tqdm

# Make project importable
PROJECT_ROOT = "/content/drive/MyDrive/NLP_project_repo"
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from src.data_loader_baseline import load_item_text, load_sequences, load_val_sequences
from src.embeddings_baseline import load_bert, extract_bert_embeddings
from src.model_baseline import BERTSASRec
from src.dataset_baseline import SeqRecDataset
from src.train_baseline import train_model
from src.evaluate_baseline import evaluate
from src.utils_baseline import build_mappings, find_item_id_by_title
from src.inference_baseline import predict_next_items_baseline

"""## Step 4: Device Setup

Configure GPU (if available) for faster training.
"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""##  Step 5: Define Data Paths

Set the base path to access dataset files after extraction.
"""

# Base path after unzip
BASE_PATH = "/content/data/Movies_and_TV/5-core/downstream"
print(BASE_PATH)

"""##  Step 6: Load Item Metadata

Load item titles from JSON file for embedding generation.
"""

item2text = load_item_text(f"/content/data/Movies_and_TV/5-core/downstream/item_titles.json")
print(item2text[list(item2text.keys())[0]])

"""## Step 7: Load Training Sequences

Load user interaction sequences for training.
"""

train_sequences = load_sequences(f"{BASE_PATH}/train_data.txt")
print(train_sequences[:3])

"""##  Step 8: Load BERT Model

Initialize pretrained BERT model and tokenizer.
"""

tokenizer, bert_model = load_bert(device)

"""##  Step 9: Generate Item Embeddings

Convert item titles into dense vector representations using BERT.
"""

item_ids, item_id_to_idx, idx_to_item, item_id_to_title, title_to_item_ids = build_mappings(item2text)
item_titles = [item2text[i] for i in item_ids]

print(f"Extracting embeddings for {len(item_titles)} items...")
item_embeddings_matrix = extract_bert_embeddings(bert_model, tokenizer, item_titles, device)

"""##  Step 10: Initialize Model

Build BERT + SASRec architecture:
- Embedding adapter layer
- Transformer encoder
- Output projection
"""

bert_sasrec_model = BERTSASRec(item_embeddings_matrix).to(device)
print("BERT + SASRec Baseline successfully initialized.")

"""##  Step 11: Prepare Dataset & DataLoader

Convert sequences into training format with:
- Padding
- Target labels
- Masking
"""

train_dataset = SeqRecDataset(train_sequences, item_id_to_idx)
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)

"""##  Step 12: Train Model

Train the model:
"""

train_model(bert_sasrec_model, train_loader, device, num_epochs=5)

"""##  Step 13: Load Validation Data

Prepare test dataset for evaluation.
"""

val_sequences = load_val_sequences(f"{BASE_PATH}/test_data.txt")
val_dataset = SeqRecDataset(val_sequences, item_id_to_idx)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)

"""## Step 14: Evaluate Model

Evaluate using:
- Recall@K
- NDCG@K
"""

metrics = evaluate(bert_sasrec_model, val_loader, device)

print("\n--- BERT Baseline Results ---")
for metric, value in metrics.items():
    print(f"{metric}: {value:.6f}")

# --- BERT Baseline Results ---
# Recall@10: 0.037661
# Recall@20: 0.052462
# NDCG@10: 0.020999
# NDCG@20: 0.024699

"""## Step 15: Inference

Predict next items based on user history.
"""

user_history = ["Avengers", "Ironman"]

preds = predict_next_items_baseline(
    model=bert_sasrec_model,
    history_titles=user_history,
    find_item_id_by_title_fn=find_item_id_by_title,
    title_to_item_ids=title_to_item_ids,
    item_id_to_idx=item_id_to_idx,
    idx_to_item=idx_to_item,
    item_id_to_title=item_id_to_title,
    device=device,
    top_k=5
)

print("\n--- BERT Baseline Inference ---")
print("User history:", user_history)
print("\nTop predictions:")
for rank, (_, title) in enumerate(preds, start=1):
    print(f"{rank}. {title}")