# -*- coding: utf-8 -*-
"""LLM2Rec_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBjBQcdnMT7lF0vQjZCpLqRDJpx4w9CD

# LLM2Rec + SASRec Recommendation System

This notebook implements a **sequential recommendation system** using:

- **LLM2Rec-derived embeddings** for item representation  
- **Transformer-based SASRec model** for sequence modeling  

### Objective
Predict the **next item a user will interact with** based on past interactions using LLM-enhanced embeddings.

## 1. Import Libraries and Setup

We initialize the environment by importing essential deep learning libraries and the Transformers suite for LLM management.
"""

# All imports here
import torch
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

"""The dataset used is the Movies and TV Amazon review dataset. We mount Google Drive, extract the raw data, and use specialized utility functions to load sequences for 7,000 users."""

from google.colab import drive
drive.mount('/content/drive')

#unzip
import zipfile
import os

ZIP_PATH = "/content/drive/MyDrive/NLP_project_repo/data/Movies_and_TV_data.zip"
EXTRACT_PATH = "/content/data"

os.makedirs(EXTRACT_PATH, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_PATH)

print(os.listdir(EXTRACT_PATH))

import sys
sys.path.insert(0, '/content/drive/MyDrive/NLP_project_repo') # Add the parent directory of src to Python path

from src.data_utils import load_data

train_file = "/content/drive/MyDrive/NLP_project_repo/data/Movies_and_TV/5-core/downstream/train_data.txt"
valid_file = "/content/drive/MyDrive/NLP_project_repo/data/Movies_and_TV/5-core/downstream/val_data.txt"
test_file = "/content/drive/MyDrive/NLP_project_repo/data/Movies_and_TV/5-core/downstream/test_data.txt"
info_file = "/content/drive/MyDrive/NLP_project_repo/data/Movies_and_TV/5-core/info/Movies_and_TV_5_2019-9-2023-10.txt"

# Ensure the 'src' directory and 'data_utils.py' are present in your Colab environment under /content/drive/MyDrive/NLP_project_repo
train_sequences, val_sequences, test_sequences, item_title_map, csft_samples = load_data(
    train_file, valid_file, test_file, info_file, max_users=7000
)

print("Train users:", len(train_sequences))
print("Validation users:", len(val_sequences))
print("Test users:", len(test_sequences))
print("Items with titles:", len(item_title_map))
print("CSFT samples:", len(csft_samples))

"""The workspace is configured to access local source modules, and the pre-trained Qwen model is loaded to serve as the backbone for the LLM2Rec system."""

import sys
sys.path.insert(0, '/content/drive/MyDrive/NLP_project_repo')


from src.csft import CSFTDataset, build_csft_loader, train_csft

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

"""The Qwen2-0.5B model and its corresponding tokenizer are instantiated with remote code execution enabled, followed by the migration of the model parameters to the GPU for optimized performance."""

#load model and Tokenizer
MODEL_NAME = "Qwen/Qwen2-0.5B"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, trust_remote_code=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

"""##2. Collaborative Soft-Fine-Tuning Dataset Construction (CSFT)

The recommendation sequences are mapped to item titles and tokenized to create the CSFT dataset, ensuring inputs are capped at 10 items and 128 tokens for model compatibility.
"""

csft_dataset = CSFTDataset(
    train_sequences=train_sequences,
    item_title_map=item_title_map,
    tokenizer=tokenizer,
    max_seq_len=10,
    max_token_len=128
)

"""The training pipeline is structured by wrapping the CSFT dataset in a data loader, which manages automated batching and sequence shuffling for the fine-tuning process."""

#create loader

csft_loader = build_csft_loader(
    dataset=csft_dataset,
    tokenizer=tokenizer,
    batch_size=4,
    shuffle=True
)

"""The AdamW optimizer is instantiated with a targeted learning rate and weight decay to regulate the model's weight updates during the CSFT phase."""

#create optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)

"""A single sample is retrieved and decoded from the dataset to verify that the item titles are correctly formatted and that the target labels align with the expected input IDs."""

sample = csft_dataset[0]

print(tokenizer.decode(sample["input_ids"]))
print(sample["labels"])

"""The CSFT training loop is executed for one epoch, utilizing gradient accumulation to stabilize updates and adapt the LLM to the specific distribution of the recommendation sequences."""

#train csft
model = train_csft(
    model=model,
    loader=csft_loader,
    optimizer=optimizer,
    device=device,
    epochs=1,
    accum_steps=2
)

"""##3. Masked Next Token Prediction (MNTP) construction

The system ensures that the latest version of the contrastive learning module is active by performing a dynamic reload before importing the specific training function for Masked Next Token Prediction (MNTP).
"""

import torch
import sys
sys.path.insert(0, '/content/drive/MyDrive/NLP_project_repo')
import importlib
import src.mntp_contrastive as mntp_module

importlib.reload(mntp_module)

train_mntp = mntp_module.train_mntp

"""IEM management: The model is patched for bidirectional attention and trained using Masked Next Token Prediction (MNTP) and contrastive learning to generate high-quality, discriminative item embeddings."""

from src.mntp_contrastive import (
    enable_bidirectional_attention,
    ItemDataset,
    item_collate_fn,
    train_mntp,
    EmbeddingModel,
    train_contrastive
)

from torch.utils.data import DataLoader

# Patch the model
model = enable_bidirectional_attention(model)

# Limit items for IEM to reduce memory use
MAX_ITEMS_FOR_IEM = 5000

limited_item_ids = list(item_title_map.keys())[:MAX_ITEMS_FOR_IEM]
item_title_map_iem = {k: item_title_map[k] for k in limited_item_ids}

print("Items used for IEM:", len(item_title_map_iem))

# Setup data
item_dataset = ItemDataset(item_title_map_iem, tokenizer)

item_loader = DataLoader(
    item_dataset,
    batch_size=16,
    shuffle=True,
    collate_fn=lambda x: item_collate_fn(x, tokenizer)
)

# Phase 1: MNTP
optimizer_mntp = torch.optim.AdamW(model.parameters(), lr=1e-5, weight_decay=0.01)
model = train_mntp(
    model=model,
    loader=item_loader,
    optimizer=optimizer,
    device=device,
    tokenizer=tokenizer,
    epochs=2,
    mask_prob=0.2
)

# Phase 2: Contrastive Learning
emb_model = EmbeddingModel(model).to(device)
optimizer_ic = torch.optim.AdamW(emb_model.parameters(), lr=1e-5, weight_decay=0.01)

emb_model = train_contrastive(
    emb_model=emb_model,
    loader=item_loader,
    optimizer=optimizer_ic,
    device=device,
    epochs=2
)

"""Extraction of latent item representation: The fine-tuned model is utilized to extract high-dimensional embeddings for the item catalog, providing the foundational feature set for the downstream recommendation task."""

import sys
import importlib

# Reload the module if it's already loaded to pick up any changes
if 'src.mntp_contrastive' in sys.modules:
    importlib.reload(sys.modules['src.mntp_contrastive'])

from src.mntp_contrastive import run_embedding_extraction

item_embeddings, item_ids = run_embedding_extraction(
    emb_model=emb_model,
    item_title_map=item_title_map_iem,
    tokenizer=tokenizer,
    device=device,
    batch_size=32,
    max_len=64
)

print("Embedding shape:", item_embeddings.shape)
print("Total item ids:", len(item_ids))

"""A dictionary is constructed to map each unique item ID to its corresponding high-dimensional vector, facilitating efficient lookup for the downstream sequence modeling phase."""

item_emb_dict = {
    item_id: item_embeddings[i]
    for i, item_id in enumerate(item_ids)
}

"""A new mapping is established to assign incremental integer indices to valid items, reserving index zero for padding to ensure compatibility with sequential modeling requirements."""

pad_idx = 0

valid_item_ids = [item_id for item_id in item_ids if item_id in item_emb_dict]

item_to_idx = {
    item_id: idx + 1
    for idx, item_id in enumerate(valid_item_ids)
}

"""A embedding lookup table is initialized and populated with the extracted latent vectors, aligning them with the newly defined item indices."""

import numpy as np

embedding_dim = item_embeddings.shape[1]

final_item_embeddings = np.zeros(
    (len(item_to_idx) + 1, embedding_dim),
    dtype=np.float32
)

for item_id, idx in item_to_idx.items():
    final_item_embeddings[idx] = item_emb_dict[item_id]
print("Final embedding matrix shape:", final_item_embeddings.shape)

"""The environment is updated to include the SASRec architecture and evaluation metrics, facilitating the transition from feature extraction to sequential model training."""

# importing the python files - sasrec, evaluation, inference
import sys
sys.path.insert(0, '/content/drive/MyDrive/NLP_project_repo') # Add the parent directory of src to Python path

from src.sasrec import SASRec, SASRecDataset
from src.evaluation import evaluate

"""##4. Self-Attentive Sequential Recommendation SASRec construction

The custom SASRec library is reloaded to ensure the most recent architectural updates are applied before importing the dataset and model classes for training.
"""

import sys
sys.path.insert(0, '/content/drive/MyDrive/NLP_project_repo')
from importlib import reload
import src.sasrec
reload(src.sasrec)

from src.sasrec import SASRecDataset, SASRec

"""The raw user interaction sequences are transformed into a supervised learning format by filtering for users with multiple interactions and splitting their history into input sequences and corresponding target items."""

train_sequences_sasrec = {}

for user_id, seq in train_sequences.items():
    if len(seq) < 2:
        continue
    train_sequences_sasrec[user_id] = (seq[:-1], seq[-1])

"""The training and validation datasets are instantiated with fixed sequence lengths and batch sizes, mapping the historical sequences to their respective indices while applying zero-padding for uniformity."""

MAX_SEQ_LEN = 10
BATCH_SIZE = 64
pad_idx = 0

train_dataset = SASRecDataset(
    sequences_dict=train_sequences_sasrec,
    item_to_idx=item_to_idx,
    max_seq_len=MAX_SEQ_LEN,
    pad_idx=pad_idx
)

val_dataset = SASRecDataset(
    sequences_dict=val_sequences,
    item_to_idx=item_to_idx,
    max_seq_len=MAX_SEQ_LEN,
    pad_idx=pad_idx
)

"""A data loader is created for the validation set to manage batching with shuffling disabled, ensuring a stable and consistent sequence for performance evaluation."""

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False
)

"""The Self-Attentive Sequential Recommendation (SASRec) model is instantiated using the LLM-derived embeddings, and the training environment is finalized with the AdamW optimizer and Cross-Entropy loss function."""

from torch.utils.data import DataLoader
from src.sasrec import SASRec
import torch

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)

sasrec_model = SASRec(
    embeddings_np=final_item_embeddings,
    hidden_dim=128,
    num_heads=2,
    num_layers=2,
    max_len=MAX_SEQ_LEN,
    dropout=0.2,
    pad_idx=pad_idx
).to(device)

optimizer_sasrec = torch.optim.AdamW(
    sasrec_model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

criterion = torch.nn.CrossEntropyLoss()

"""The model undergoes supervised training over 10 epochs, employing gradient clipping and the AdamW optimizer to minimize cross-entropy loss across the sequenced interaction data."""

EPOCHS = 10

for epoch in range(EPOCHS):
    sasrec_model.train()
    total_loss = 0.0

    for batch in train_loader:
        item_seq = batch["item_seq"].to(device)
        padding_mask = batch["padding_mask"].to(device)
        targets = batch["target"].to(device)

        optimizer_sasrec.zero_grad()

        scores = sasrec_model(item_seq, padding_mask)
        loss = criterion(scores, targets)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(sasrec_model.parameters(), 1.0)
        optimizer_sasrec.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}, Train Loss: {avg_loss:.4f}")

from src.evaluation import evaluate

metrics = evaluate(sasrec_model, val_loader, device, k_list=[10, 20])
print("\nFinal Test Results")
print("Recall@10 :", round(metrics["Recall@10"], 8))
print("NDCG@10   :", round(metrics["NDCG@10"], 8))
print("Recall@20 :", round(metrics["Recall@20"], 8))
print("NDCG@20   :", round(metrics["NDCG@20"], 8))


# Final Test Results
# Recall@10 : 0.0034632
# NDCG@10   : 0.00125477
# Recall@20 : 0.004329
# NDCG@20   : 0.00148256

"""The system imports specialized functions for title-to-ID resolution and next-item prediction, enabling the model to generate human-readable recommendations from user interaction histories."""

from src.inference import find_item_id_by_title,search_titles,predict_next_items,build_title_maps

"""Two-way mapping dictionaries are generated to facilitate seamless translation between internal model indices and human-readable item titles for inference."""

idx_to_item, title_to_item_ids = build_title_maps(item_title_map_iem, item_to_idx)

"""The trained SASRec model is deployed to predict the top 20 most relevant next items based on a specific user history, demonstrating the system's ability to generalize patterns from superhero and action-themed sequences."""

recommendations = predict_next_items(
    model=sasrec_model,
    history_titles=["Avengers", "Iron Man"],
    item_to_idx=item_to_idx,
    idx_to_item=idx_to_item,
    item_title_map=item_title_map_iem,
    title_to_item_ids=title_to_item_ids,
    max_seq_len=10,
    pad_idx=0,
    top_k=20
)
for i, (_, title) in enumerate(recommendations, start=1):
    print(f"{i}. {title}")

"""**Superhero & High-Tech Action**

Black Adam

Hulk Vs.

King of the Rocket Men

**Sci-Fi Adventure & Space Opera**

The Fifth Element

Serenity

Harlock: Space Pirate

Land That Time Forgot

2001: A Space Odyssey

**Tactical Action & Sci-Fi Thriller**

Six (Season 1 & 2)

They Live

The Getaway (1972)

The recommendation output demonstrates the effectiveness of integrating LLM-derived embeddings with a Self-Attentive (SASRec) architecture, even when constrained to a 7,000-user subset.

plotting
"""

sasrec_train_losses = []
sasrec_val_losses = []

for epoch in range(EPOCHS):
    # Training Phase
    sasrec_model.train()
    total_train_loss = 0.0
    for batch in train_loader:
        item_seq, padding_mask, targets = batch["item_seq"].to(device), batch["padding_mask"].to(device), batch["target"].to(device)
        optimizer_sasrec.zero_grad()
        scores = sasrec_model(item_seq, padding_mask)
        loss = criterion(scores, targets)
        loss.backward()
        optimizer_sasrec.step()
        total_train_loss += loss.item()

    # Validation Phase
    sasrec_model.eval()
    total_val_loss = 0.0
    with torch.no_grad():
        for batch in val_loader:
            item_seq, padding_mask, targets = batch["item_seq"].to(device), batch["padding_mask"].to(device), batch["target"].to(device)
            scores = sasrec_model(item_seq, padding_mask)
            val_loss = criterion(scores, targets)
            total_val_loss += val_loss.item()

    sasrec_train_losses.append(total_train_loss / len(train_loader))
    sasrec_val_losses.append(total_val_loss / len(val_loader))
    print(f"Epoch {epoch+1} | Train Loss: {sasrec_train_losses[-1]:.4f} | Val Loss: {sasrec_val_losses[-1]:.4f}")

plt.figure(figsize=(8, 5))
plt.plot(range(1, EPOCHS + 1), sasrec_train_losses, label='Train Loss', marker='o', color='#1f77b4')
plt.plot(range(1, EPOCHS + 1), sasrec_val_losses, label='Val Loss', marker='s', color='#ff7f0e')

plt.title("SASRec Model: Training vs Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""#Analysis of Loss Trends

### Diverging Loss Paths
* **Training Loss:** Shows a steady decline from **7.5581** to **7.2109**. This indicates the model is successfully learning to predict the specific sequences present in your training set.
* **Validation Loss:** Starts at **9.4252** and consistently **increases** every epoch, reaching **10.6392**.

The divergence between a falling training loss and a rising validation loss suggests that the model is **memorizing noise** rather than generalizing patterns.




"""